# Generated by Django 5.2.15 on 2026-06-21 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_shelter',
            field=models.ForeignKey(blank=True, help_text='For rescuer accounts only. Admin verifies and links the rescuer to a shelter.', limit_choices_to={'role': 'SHELTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_rescuers', to=settings.AUTH_USER_MODEL, verbose_name='Linked Shelter'),
        ),
        migrations.AddField(
            model_name='user',
            name='shelter_address',
            field=models.CharField(blank=True, help_text='Required for shelter accounts. This is the default handover location for rescued animals.', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='shelter_map_link',
            field=models.URLField(blank=True, help_text='Optional Google Maps or Apple Maps link for the shelter handover location.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_area',
            field=models.CharField(blank=True, help_text='Required for shelter accounts. Example: Colombo, Kottawa, Maharagama.', max_length=100),
        ),
    ]
