# Generated by Django 5.2.15 on 2026-06-27 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_linked_shelter_user_shelter_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='linked_shelter',
            field=models.ForeignKey(blank=True, help_text='For rescuer accounts only. The rescuer selects the shelter they are connected with.', limit_choices_to={'role': 'SHELTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_rescuers', to=settings.AUTH_USER_MODEL, verbose_name='Linked Shelter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_area',
            field=models.CharField(blank=True, help_text='For shelter accounts only. Example: Kottawa, Maharagama, Homagama.', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='shelter_address',
            field=models.CharField(blank=True, help_text='For shelter accounts only. This is used as the shelter handover location.', max_length=255),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FAKE_ACCOUNT', 'Fake Account'), ('MISLEADING_INFORMATION', 'Misleading Information'), ('NOT_LINKED_TO_SHELTER', 'Not Actually Linked to Selected Shelter'), ('SUSPICIOUS_BEHAVIOUR', 'Suspicious Behaviour'), ('INAPPROPRIATE_BEHAVIOUR', 'Inappropriate Behaviour'), ('SCAM_OR_FRAUD', 'Scam or Fraud Concern'), ('OTHER', 'Other')], max_length=40)),
                ('description', models.TextField(help_text='Explain why this account is being reported.')),
                ('related_page', models.CharField(blank=True, help_text='Optional page or workflow where the suspicious activity was noticed.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('ACTION_TAKEN', 'Action Taken'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes after reviewing the report.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_user_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_user_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Safety Report',
                'verbose_name_plural': 'User Safety Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
