# Generated by Django 5.2.15 on 2026-06-30 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_account_status_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REPORT_REVIEWED', 'Report Reviewed'), ('CASE_ASSIGNED', 'Case Assigned'), ('RESCUE_UPDATE', 'Rescue Update'), ('TREATMENT_UPDATE', 'Treatment Update'), ('ADOPTION_REQUEST', 'Adoption Request'), ('ADOPTION_DECISION', 'Adoption Decision'), ('ACCOUNT_SAFETY_REPORT', 'Account Safety Report'), ('GENERAL', 'General')], default='GENERAL', max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('target_url', models.CharField(blank=True, help_text='Optional page link related to this notification.', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
