# Generated by Django 5.2.15 on 2026-06-18 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('OTHER', 'Other')], max_length=20)),
                ('other_animal_type', models.CharField(blank=True, help_text='Required only when animal type is Other.', max_length=100)),
                ('condition', models.CharField(choices=[('SEVERE_INJURY', 'Severe Injury'), ('ROAD_ACCIDENT', 'Road Accident'), ('BLEEDING', 'Bleeding'), ('SICK', 'Sick'), ('MINOR_INJURY', 'Minor Injury'), ('ABANDONED', 'Abandoned'), ('LOST', 'Lost'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Describe the animal condition and situation.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_description', models.CharField(help_text='Example: Near Kottawa bus stand, beside the main road.', max_length=255)),
                ('map_link', models.URLField(blank=True, help_text='Optional pasted Google Maps or Apple Maps link.')),
                ('suggested_priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], help_text='Final priority is selected manually by shelter.', max_length=10)),
                ('report_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('ASSIGNED', 'Assigned'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_shelter', models.ForeignKey(blank=True, limit_choices_to={'role': 'SHELTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
