# Generated by Django 5.2.15 on 2026-06-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter_contact_phone',
            field=models.CharField(blank=True, help_text='Required when submitting a report so the shelter can verify the animal location.', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from shelter after contacting the reporter.'),
        ),
        migrations.AddField(
            model_name='report',
            name='verification_status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('CONFIRMED_STILL_THERE', 'Confirmed Still There'), ('ANIMAL_NOT_FOUND', 'Animal Not Found / Moved'), ('ALREADY_RESCUED', 'Already Rescued')], default='PENDING_VERIFICATION', max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
