# Generated by Django 5.2.15 on 2026-06-19 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0002_report_reporter_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_rescuer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'RESCUER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescuer_assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='assignment_notes',
            field=models.TextField(blank=True, help_text='Optional notes from shelter for the assigned rescuer.'),
        ),
    ]
