# Generated by Django 5.2.15 on 2026-06-20 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0003_report_assigned_at_report_assigned_rescuer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='current_rescue_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ON_THE_WAY', 'On the Way'), ('RESCUED', 'Rescued'), ('UNABLE_TO_LOCATE', 'Unable to Locate')], default='NOT_STARTED', max_length=30),
        ),
        migrations.CreateModel(
            name='RescueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ON_THE_WAY', 'On the Way'), ('RESCUED', 'Rescued'), ('UNABLE_TO_LOCATE', 'Unable to Locate')], max_length=30)),
                ('update_text', models.TextField(help_text='Write the rescue progress update.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rescue_update_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_updates', to='rescue.report')),
                ('rescuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
