# Generated by Django 5.2.15 on 2026-06-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0004_report_current_rescue_status_rescueupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assignment_notes',
            field=models.TextField(blank=True, help_text='Rescue and handover instructions for the assigned rescuer.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='current_rescue_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ON_THE_WAY', 'On the Way'), ('RESCUED', 'Rescued'), ('UNABLE_TO_LOCATE', 'Unable to Locate'), ('HANDED_OVER_TO_SHELTER', 'Handed Over to Shelter')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='rescueupdate',
            name='status',
            field=models.CharField(choices=[('ON_THE_WAY', 'On the Way'), ('RESCUED', 'Rescued'), ('UNABLE_TO_LOCATE', 'Unable to Locate'), ('HANDED_OVER_TO_SHELTER', 'Handed Over to Shelter')], max_length=30),
        ),
    ]
