# Generated by Django 5.2.15 on 2026-06-22 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0005_alter_report_assignment_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name given by the shelter.', max_length=100)),
                ('age', models.CharField(blank=True, help_text='Approximate age. Example: Puppy, Adult, 2 years, Unknown.', max_length=50)),
                ('gender', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='UNKNOWN', max_length=20)),
                ('animal_image', models.ImageField(blank=True, help_text='Optional updated image after the animal reaches the shelter.', null=True, upload_to='animal_images/')),
                ('health_status', models.TextField(blank=True, help_text='Current health condition of the animal.')),
                ('treatment_status', models.CharField(choices=[('UNDER_TREATMENT', 'Under Treatment'), ('RECOVERING', 'Recovering'), ('READY_FOR_ADOPTION', 'Ready for Adoption'), ('ADOPTED', 'Adopted'), ('PASSED_AWAY', 'Passed Away')], default='UNDER_TREATMENT', max_length=30)),
                ('treatment_notes', models.TextField(blank=True, help_text='Treatment progress notes added by the shelter.')),
                ('vet_info', models.CharField(blank=True, help_text='Vet clinic or veterinarian details, if available.', max_length=255)),
                ('arrival_date', models.DateField(blank=True, help_text='Date the animal arrived at the shelter or treatment location.', null=True)),
                ('adoption_ready_date', models.DateField(blank=True, help_text='Date the animal became ready for adoption.', null=True)),
                ('outcome_date', models.DateField(blank=True, help_text='Date of final outcome, such as adoption or passing away.', null=True)),
                ('outcome_notes', models.TextField(blank=True, help_text='Optional notes about the final outcome of the case.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_rescuer', models.ForeignKey(blank=True, limit_choices_to={'role': 'RESCUER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescued_animals', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='rescue.report')),
                ('shelter', models.ForeignKey(blank=True, limit_choices_to={'role': 'SHELTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelter_animals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
